version: "3"

services:

  bot:
    build:
      context: .
    container_name: tonutils-assistant-bot
    command: sh -c "cd /usr/src/bot && python -m bot"
    restart: always
    volumes:
      - .:/usr/src/bot
